services:
  mysql:
    image: mysql:8
    container_name: workinsight-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workinsight
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: workinsight-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - "./backend:/app"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/workinsight
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      JWT_SWECRET: ThisIsSuperSecureJwtSecretKey1234567890

volumes:
  db-data:
