services:
  mysql:
    image: mysql:8
    container_name: workinsight-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workinsight
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: workinsight-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/workinsight
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  db-data:
